apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: socks-shop
namePrefix: dev-
commonLabels:
  environment: socks-shop
images:
- name: weaveworksdemos/payment
  newTag: latest
bases:
- ../../base

